// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfssuewzrvhatnwolmnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmc3N1ZXd6cnZoYXRud29sbW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDQ4MjEsImV4cCI6MjA2Mzk4MDgyMX0.v_XvYaUwGMknFOXLtpcl4e4PASU9ICFh8go_zohtsSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);